# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/new/DirectionReaction.vhd
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/new/Enabler.vhd
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/new/HexMux.vhd
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/new/LEDMux.vhd
  {C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/imports/VHDL-hjælpekode og sol/MuxDisplay.vhd}
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/new/Reactions.vhd
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/imports/VHDL-hjælpekode/VGA_Core2.vhd
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/imports/VHDL-hjælpekode/VGA_Driver.vhd
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/imports/VHDL-hjælpekode/VGA_Top.vhd
  C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/sources_1/new/MiniGames_Top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/constrs_1/imports/Basys 3 kit/Basys3_Master_VGA.xdc}}
set_property used_in_implementation false [get_files {{C:/Xilinx/Projekter/Portfolio2_Lab/Portfolio2_Lab.srcs/constrs_1/imports/Basys 3 kit/Basys3_Master_VGA.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MiniGames_Top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MiniGames_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MiniGames_Top_utilization_synth.rpt -pb MiniGames_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
