# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Basys 3 kit/Basys3_Master_VGA.xdc

# Block Designs: bd/ScopeDesign/ScopeDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign || ORIG_REF_NAME==ScopeDesign} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_blk_mem_gen_0_0/ScopeDesign_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_blk_mem_gen_0_0 || ORIG_REF_NAME==ScopeDesign_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_OffsetGain_ZoomPan_0_0/ScopeDesign_OffsetGain_ZoomPan_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_OffsetGain_ZoomPan_0_0 || ORIG_REF_NAME==ScopeDesign_OffsetGain_ZoomPan_0_0} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_RotaryModule_0_0/ScopeDesign_RotaryModule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_RotaryModule_0_0 || ORIG_REF_NAME==ScopeDesign_RotaryModule_0_0} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_VGA_Core2_0_0/ScopeDesign_VGA_Core2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_VGA_Core2_0_0 || ORIG_REF_NAME==ScopeDesign_VGA_Core2_0_0} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_VGA_Driver_0_0/ScopeDesign_VGA_Driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_VGA_Driver_0_0 || ORIG_REF_NAME==ScopeDesign_VGA_Driver_0_0} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_VGA_Top_0_0/ScopeDesign_VGA_Top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_VGA_Top_0_0 || ORIG_REF_NAME==ScopeDesign_VGA_Top_0_0} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_MuxDisplay_0_1/ScopeDesign_MuxDisplay_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_MuxDisplay_0_1 || ORIG_REF_NAME==ScopeDesign_MuxDisplay_0_1} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_ADC_interface_0_0/ScopeDesign_ADC_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_ADC_interface_0_0 || ORIG_REF_NAME==ScopeDesign_ADC_interface_0_0} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_xlconstant_0_2/ScopeDesign_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_xlconstant_0_2 || ORIG_REF_NAME==ScopeDesign_xlconstant_0_2} -quiet] -quiet

# IP: bd/ScopeDesign/ip/ScopeDesign_xlconstant_1_0/ScopeDesign_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ScopeDesign_xlconstant_1_0 || ORIG_REF_NAME==ScopeDesign_xlconstant_1_0} -quiet] -quiet

# XDC: bd/ScopeDesign/ScopeDesign_ooc.xdc
