# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Basys 3 kit/Basys3_Master.xdc

# Block Designs: bd/MegaMux/MegaMux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MegaMux || ORIG_REF_NAME==MegaMux} -quiet] -quiet

# IP: bd/MegaMux/ip/MegaMux_Mux1x2_0_0/MegaMux_Mux1x2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MegaMux_Mux1x2_0_0 || ORIG_REF_NAME==MegaMux_Mux1x2_0_0} -quiet] -quiet

# IP: bd/MegaMux/ip/MegaMux_Mux1x2_0_1/MegaMux_Mux1x2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MegaMux_Mux1x2_0_1 || ORIG_REF_NAME==MegaMux_Mux1x2_0_1} -quiet] -quiet

# IP: bd/MegaMux/ip/MegaMux_Mux1x2_0_2/MegaMux_Mux1x2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MegaMux_Mux1x2_0_2 || ORIG_REF_NAME==MegaMux_Mux1x2_0_2} -quiet] -quiet

# IP: bd/MegaMux/ip/MegaMux_xlconcat_0_1/MegaMux_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MegaMux_xlconcat_0_1 || ORIG_REF_NAME==MegaMux_xlconcat_0_1} -quiet] -quiet

# XDC: bd/MegaMux/MegaMux_ooc.xdc
